import requests
import base64
from io import BytesIO
from config import TTS_API_KEY  # store your ElevenLabs key here

try:
    from gtts import gTTS
except Exception:
    gTTS = None


def _sanitize_text(text):
    cleaned = " ".join(str(text or "").split())
    return cleaned.strip()


def _split_text_chunks(text, max_chars=180):
    """Split long text into sentence-like chunks for fallback TTS providers."""
    cleaned = _sanitize_text(text)
    if len(cleaned) <= max_chars:
        return [cleaned]

    chunks = []
    current = ""
    separators = [".", "!", "?", "\n", "।"]

    def flush():
        nonlocal current
        if current.strip():
            chunks.append(current.strip())
        current = ""

    for token in cleaned.split(" "):
        next_value = (current + " " + token).strip() if current else token
        if len(next_value) <= max_chars:
            current = next_value
            if any(token.endswith(sep) for sep in separators):
                flush()
        else:
            flush()
            if len(token) <= max_chars:
                current = token
            else:
                # Hard split single oversized token.
                for i in range(0, len(token), max_chars):
                    chunks.append(token[i:i + max_chars])

    flush()
    return [chunk for chunk in chunks if chunk]


def _elevenlabs_tts(text):
    url = "https://api.elevenlabs.io/v1/text-to-speech/JBFqnCBsd6RMkjVDRZzb"  # voice ID

    headers = {
        "xi-api-key": TTS_API_KEY,
        "Content-Type": "application/json"
    }

    payload = {
        "text": _sanitize_text(text),
        "model_id": "eleven_turbo_v2_5",  # supports multilingual including Kannada
        "voice_settings": {
            "stability": 0.5,
            "similarity_boost": 0.75
        }
    }

    response = requests.post(url, json=payload, headers=headers, timeout=45)
    response.raise_for_status()
    return response.content


def _gtts_fallback(text):
    if gTTS is None:
        raise RuntimeError("gTTS is not installed for fallback TTS.")

    audio_buffer = BytesIO()
    tts = gTTS(text=_sanitize_text(text), lang="kn", slow=False)
    tts.write_to_fp(audio_buffer)
    return audio_buffer.getvalue()


def _http_tts_fallback(text):
    """Dependency-free fallback using Google Translate TTS endpoint."""
    url = "https://translate.google.com/translate_tts"
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/124.0.0.0 Safari/537.36"
        )
    }
    audio_parts = []
    for chunk in _split_text_chunks(text):
        params = {
            "ie": "UTF-8",
            "q": chunk,
            "tl": "kn",
            "client": "tw-ob",
        }
        response = requests.get(url, params=params, headers=headers, timeout=45)
        response.raise_for_status()
        audio_parts.append(response.content)

    if not audio_parts:
        raise RuntimeError("No audio generated by HTTP fallback.")

    return b"".join(audio_parts)

def text_to_kannada_speech(text):
    normalized_text = _sanitize_text(text)
    if not normalized_text:
        raise ValueError("Text for TTS is empty.")

    primary_error = None

    try:
        audio_bytes = _elevenlabs_tts(normalized_text)
        return base64.b64encode(audio_bytes).decode("utf-8")
    except Exception as error:
        primary_error = error

    # Fallback path when ElevenLabs blocks free-tier usage or rate limits.
    try:
        audio_bytes = _gtts_fallback(normalized_text)
        return base64.b64encode(audio_bytes).decode("utf-8")
    except Exception as fallback_error:
        try:
            audio_bytes = _http_tts_fallback(normalized_text)
            return base64.b64encode(audio_bytes).decode("utf-8")
        except Exception as http_fallback_error:
            raise Exception(
            f"TTS failed on primary and fallback providers. "
            f"Primary error: {primary_error}. "
            f"gTTS fallback error: {fallback_error}. "
            f"HTTP fallback error: {http_fallback_error}"
        )


# TEST
if __name__ == "__main__":
    audio = text_to_kannada_speech(
        "ನಿಮ್ಮ ಔಷಧಿ ಸುರಕ್ಷಿತವಾಗಿದೆ"
    )
    print("Success! Audio length:", len(audio))

    # Optional: save to file to verify
    with open("output.mp3", "wb") as f:
        f.write(base64.b64decode(audio))
    print("Saved as output.mp3")
